server:
  port: 1003
  context-path: /

# 数据源配置
spring:
  application:
    name: microservice-student  #定义应用的名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springcloud?serverTimezone=GMT&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: microservice-student  #客户端服务名
    instance-id: microservice-student:1003 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      # defaultZone: http://localhost:1083/eureka   #把服务注册到eureka注册中心
      defaultZone: http://dd1.linka39.top:1083/eureka/,http://dd2.linka39.top:1084/eureka/ # 集群

info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version: $project.version$
  负责人: 王五
  联系电话: 110
